import { signUpFormSchema } from '@/lib/form-schema';
import { zodResolver } from '@hookform/resolvers/zod';
import { Metadata } from 'next';
import React, { FC } from 'react'
import { useForm } from 'react-hook-form';
import { z } from 'zod';

interface SignUpPageProps {

}

export const metadata: Metadata = {
  title: "Sign Up",
  description: "Generated by create next app",
};

const SignUpPage: FC<SignUpPageProps> = ({  }) => {

  const form = useForm<z.infer<typeof signUpFormSchema>>({
    resolver: zodResolver(signUpFormSchema)
  })

  const onSubmit = (val: z.infer<typeof signUpFormSchema>) => {
    console.log(val);
  }
  return (
    <div>
     SignUpPage
    </div>
  )
}

export default SignUpPage;